### PR TITLE
plugin modernization

### PR DESCRIPTION
**Pull request by mawinter69**
- build against Java 17 and use newer LTS as baseline
- the javascript contained some prototype code
- removed yui code and converted the Panel to html tooltips
- remove the yui compressor as it doesn't support modern javascript

After:
image

### Testing done
Manually tested

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mawinter69** [comment]
@olamy could you take a look

**Comment by timja** [comment]
@olamy could you take a look please?

**Comment by olamy** [comment]
LGTM.
But TBH I;m not really maintaining this plugin anymore

**Comment by timja** [comment]
> LGTM. But TBH I;m not really maintaining this plugin anymore

Thanks for merging! Any chance of a release please? (this is one of the last plugins for the YUI removal)

**Comment by olamy** [comment]
done

**Pull request merged**
